services:
  mongo:
    image: mongo:latest
    container_name: df-lfg-bot-Mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: DOWbot
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    networks:
      - df-lfg-bot-Network

volumes:
  mongo-data:
    driver: local
  mongo-config:
    driver: local

networks:
  df-lfg-bot-Network:
    driver: bridge
